language: node_js

node_js:
  - "8"

script: npm run test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

before_script:
  - yarn add codecov --ignore-workspace-root-check
  - npm run bootstrap

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
    - packages/site/node_modules
    - packages/react-emotion/node_modules
    - packages/preact-emotion/node_modules
    - packages/babel-plugin-emotion/node_modules
    - packages/emotion-utils/node_modules
    - packages/benchmarks/node_modules
    - packages/emotion-server/node_modules
    - packages/emotion/node_modules
